### ISSUE TITLE
fbzmq publisher unable to publish on topic

### ISSUE THREAD

**Issue by marktam264** [facebook/fbzmq#12]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue Description
From the current documentation and examples, it is unclear to me whether the API supports publishing a message on a specific topic.  Is this possible using the fbzmq API?

# Environment

* tag or commit hash on which this occured
* OS version: <e.g. ubuntu-16.04>
Mint 18.3 (Ubuntu 16.04)

# Minimal test code / Steps to reproduce the issue

# What's the actual result?
Current send*() methods on the API do not seem to support publishing on a topic for a ZMQ_PUB socket.

# What's the expected result?
send*() methods on the API have a parameter to publish on a topic.

**Comment by saifhhasan** [comment]
Yes it is possible. Use sendMultiple method. Something on the lines of

```
socket.sendMultiple(
  fbzmq::Message::from(std::string("topic")),
  fbzmq::Message::from(std::string("data")));
```

**Comment by marktam264** [comment]
@saihhasan, thank you, yes that would work.

Although, I still think it would be ideal if we could put the responsibility of routing into fbzmq (via topics) rather than putting it on the client to do so.

**Comment by saifhhasan** [comment]
@marktam264 hmm. I would dis-agree here. We tried to keep fbzmq as a C++ wrapper over libzmq (C version). So things like migrating existing code, or just getting started with fbzmq with understanding of libzmq is straight forward :)

**Comment by marktam264** [comment]
@saifhhasan no problem.  Yes, it is straight forward if you know libzmq.  Thank you, again.
