### ISSUE TITLE
Update deps_common.sh, please

### ISSUE THREAD

**Issue by trosan** [facebook/fbzmq#5]
# Issue Description
The current dependency install script seems to be out of date.
I experienced the following issues:
* THRIFT_COMPILER_INCLUDE was set to NOTFOUND and I had to manually download the ThriftLibrary.cmake since the current script points to a tag that does not contain this script (and had to set to that path manually - how is it supposed to be set?)
* Afterwards PROTOCOL and TRANSPORT are still set to NOTFOUND and I have no clue as to which libraries these are.

# Environment

* master branch, latest commit b542717b9af4a1fe29581561761b38a2373d9eac
* OS version: ubuntu-16.04
...

# Minimal test code / Steps to reproduce the issue
* setup clean ubuntu 16.04 vm, clone git, run deps_ubuntu_16.04.sh, run "cmake .."

# What's the actual result?

* "CMake Error at CMakeLists.txt:32 (include):
  include could not find load file:

    THRIFT_COMPILER_INCLUDE-NOTFOUND/thrift/ThriftLibrary.cmake

  CMake Error at CMakeLists.txt:40 (thrift_object):
    Unknown CMake command "thrift_object".

  -- Configuring incomplete, errors occurred!
  See also "/home/c1/fbzmq/fbzmq/build/CMakeFiles/CMakeOutput.log"."

and:
* "CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PROTOCOL
    linked by target "fbzmq" in directory /home/c1/fbzmq/fbzmq
TRANSPORT
    linked by target "fbzmq" in directory /home/c1/fbzmq/fbzmq"

# What's the expected result?
* cmake should run without errors

**Comment by jstrizich** [comment]
Sorry for the delay. We've updated the build script and directions for it in the top level readme. Please let us know if there are still issues and always feel free to put up a pull request with fixes.
