### ISSUE TITLE
fbzmq memory model

### ISSUE THREAD

**Issue by kreuzerkrieg** [facebook/fbzmq#7]
Hi,
Quick question. Somewhere in the build script I saw `jemalloc` mentioned. How it would play with my application that uses `tcmalloc` tailored to work with shared memory allocated on hugepages? can I disable `jemalloc`? Can I (easily) replace it with my `tcmalloc` implementation?
Sincerely,
Ernest

**Comment by jstrizich** [comment]
Ernest, I can't foresee any major issues with changing your malloc flavor. Please feel free to experiment and let us know how it goes.

**Comment by kreuzerkrieg** [comment]
I guess there is some misunderstanding, I dont want to change my malloc flavour, I want to keep my tcmalloc, the question is, how is the  `fbzmq` going to survive it

**Comment by kreuzerkrieg** [comment]
Yep, I think this is what I gonna do, since I guess noone knows the answer. Will report back when will integrate with our app.

**Comment by jstrizich** [comment]
Yes, that is your best bet. Will close this for now
