### ISSUE TITLE
fbzmq threading model

### ISSUE THREAD

**Issue by kreuzerkrieg** [facebook/fbzmq#9]
Hi,
I have a question about processing messages the right way. I see that the socked callback attached to the socket is executed in the same thread where the server's (referring to example server) method `run()` is called. Meaning it would kill any asynchronous calls to the server since the message processing (I guess message receiving made on zmq polling threads) may take a long time, and thus blocking parallel message processing. What is the right approach to employ in `fbzmq`? is there any build-in mechanism to offload message processing to a worker thread pool? Should I use my own? If later, how socket callback should treat the `sendOne` part of the server?
Sincerely,
E

**Comment by saifhhasan** [comment]
Hello, 

ZMQ  internally has multiple IO threads (configurable when you create context). These threads are responsible for actually performing IO. Socket read/recv are just commands exchanged between ZMQ socket interface and actual IO threads (often there is 1 IO thread as it can serve upto several Gbps of throughput as per ZMQ's doc).

Give a shot to what you intend to do and ZMQ's architecture should be able to handle it with scale you intend.

Once message is received you can pass it to worker thread or do processing yourself. In former case you will need method to interact between threads. 


NOTE: fbzmq is just a thin wrapper over the ZeroMQ library in C, with some additional constructs that makes programming in C++ easier and less error prone with ZMQ.

**Comment by saifhhasan** [comment]
You add socket to event loop ... There are two ways to send reply I can think of
- When you receive an event on socket and send response to the same socket or other
- Or timeout that occurs in loop (EventLoop supports scheduling timeouts), which will invoke callback function and it can send message to socket.

One thing to note here is that, if callback is invoked that means message is always ready to read so you can read with NON_BLOCKING flag to avoid getting blocked.

I think what you're asking here is general async programming question. You might like to refer to some guides available online to achieve that.

**Comment by kreuzerkrieg** [comment]
@saifhhasan, I dont think this question is in any way related to async programming. It is a question of `zmq` patterns to employ in such a case. For example, the answer may be [`Paranoid Pirate Pattern`](http://zguide.zeromq.org/page:all#Robust-Reliable-Queuing-Paranoid-Pirate-Pattern) which is described in the `zmq` guide.
